name: dnl
version: '18'
author: HexNowLoading
description: A dungeon made by Hex

data_pack:
  load: [src]
  zipped: false

output: 'build'

require:
  - bolt
  - bolt_expressions
  - reapermc

pipeline:
  - mecha
  - plugins.remove_empty_files

meta:
  bolt:
    entrypoint:
      - dnl:*
  dnl:
    namespace: 'dnl'
    cmd_namespace: 'cmd'
    datapack_version: 18
  config:
